version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7243
      POSTGRES_DB: geoService
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: