"""create conversation, Message tables

Revision ID: 184d5f99c369
Revises: 904d5d1e36b8
Create Date: 2024-11-07 17:52:40.904559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "184d5f99c369"
down_revision: Union[str, None] = "904d5d1e36b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Conversations",
        sa.Column("last_message_date", sa.DateTime(), nullable=True),
        sa.Column("last_message_text", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Messages",
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["Conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_user_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("users", sa.Integer(), nullable=False),
        sa.Column("conversations", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversations"],
            ["Conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "users", "conversations", name="inx_unique_user_conversation"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_user_association")
    op.drop_table("Messages")
    op.drop_table("Conversations")
    # ### end Alembic commands ###
